[package]
name = "register_access"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "1.0.1"
embedded-hal = "1.0.0"
embedded-hal-async = {version = "1.0.0", optional = true}
paste = "1.0.15"



[features]
default = []
async = ["dep:embedded-hal-async"]
blocking = []
